version: '2'
services:
  redis:
    image: redis
    networks:
      - back-end
  db:
    image: postgres:9.4
    networks:
      - back-end
  vote:
    image: voting-app
    networks:
      - fornt-end
      - back-end
  result:
    image: result
    networks:
      - fornt-end
      - back-end

networks:
  fornt-end
  back-end