redis:
  image: redis

db:
  image: postgres:9.4

vote:
  image: voting-app
  ports:
    - 5000:80
  links:
    - redis:redis

result:
  image: result-app
  ports:
    - 5001:80
  links:
    - db:db

worker:
  image: worker
  links:
    - redis:redis
    - db:db