version: "3"
services:
  redis:
    image: redis

  vote:
    image: votting-app
    ports:
      - 5000:80
  
  data:
    image: postgres:9.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:

    ports:
      - 5432:5432

  
  worker:
    image: worker-app

  
  result:
    image: result-app
    ports:
      - 5001:80