version: '3'
services:
  redis:
    image: redis
    deploy:
      replicas: 3

  db:
    image: postgres:9.4
    deploy:
      replicas: 3

  vote:
    image: dockersamples/examplevotingapp_vote
    ports:
      - 5000:80
    deploy:
      replicas: 3


  worker:
    image: dockersamples/examplevotingapp_worker
    deploy:
      replicas: 3

  result:
    image: dockersamples/examplevotingapp_result
    ports:
      - 5001:80
    deploy:
      replicas: 4
