version: '3'
services:
  redis:
    image: redis
    deploy:
            placement:
                    constraints:
                            - node.hostname == docker-worker1.cs.net
            replicas: 10

  db:
    image: postgres:9.4
    deploy:
            placement:
                    constraints:
                            - node.hostname == docker-worker2.cs.net
            replicas: 2

  vote:
    image: dockersamples/examplevotingapp_vote
    ports:
      - 5000:80
    deploy:
            placement:
                    constraints:
                            - node.hostname == docker-worker1.cs.net
            replicas: 7


  worker:
    image: dockersamples/examplevotingapp_worker
    deploy:
            placement:
                    constraints:
                            - node.hostname == docker-worker2.cs.net
            replicas: 3

  result:
    image: dockersamples/examplevotingapp_result
    ports:
      - 5001:80
    deploy:
            placement:
                    constraints:
                            - node.hostname == docker-worker1.cs.net
            replicas: 12
