version: '3'
services:
  config-server:
    image: harbor-mra.cellosco.pe/mra/cloud-config:v2
    ports:
      - 8888:8888
    deploy:
      placement:
        constraints:
          - node.role != manager
          #- node.labels.environment != worker1
          - node.hostname != docker-worker1.cs.net
          #- node.hostname == docker-worker3.cs.net
        preferences:
          - spread: node.hostname == docker-worker3.cs.net
      replicas: 1
    volumes:
      - mra_config:/var/log/mra/config-server


volumes:
  mra_config: