version: '3'
services:
  redis:
    image: redis
    deploy:
      placement:
        constraints:
          - node.role != manager
      replicas: 3
      restart_policy:
        condition: on-failure

  db:
    image: postgres:9.4
    deploy:
      placement:
        constraints:
          - node.role != manager
      replicas: 3
      restart_policy:
        condition: on-failure

  vote:
    image: dockersamples/examplevotingapp_vote
    ports:
      - 5000:80
    deploy:
      placement:
        constraints:
          - node.role != manager
      replicas: 3
      restart_policy:
        condition: on-failure


  worker:
    image: dockersamples/examplevotingapp_worker
    deploy:
      placement:
        constraints:
          - node.role != manager
      replicas: 3
      restart_policy:
        condition: on-failure

  result:
    image: dockersamples/examplevotingapp_result
    ports:
      - 5001:80
    deploy:
      placement:
        constraints:
          - node.role != manager
      replicas: 3
      restart_policy:
        condition: on-failure