version: '3'
services:
    redis:
      image: redis

    db:
      image: postgres:9.4
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres

    vote:
      image: app-voting
      ports:
        - 5000:80
      #links:
        #- redis

    worker:
      image: app-worker
      #links:
        #- redis
        #- db

    result:
      image: app-result
      ports:
        - 5001:80
      #links:
        #- db